### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by jmealo** [ivanmb/ims-lti#1]
Hello,

Kudos on your PHP port of instructure/ims-lti.

instructure/ims-lti is released under the MIT license, however, there's no LICENSE file in this repo.

Could you please include whatever licenses this code is released under?

Thanks,
Jeff

**Comment by ivanmb** [comment]
Added MIT License! I'm not working on this right now, but if you need some missing functionality, please fork and make a pull request.

Thanks!
